name: reena
favicon: null
layout_spectrum: 0.658988292561844
typography_spectrum: 0.5484060179442167
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8491381958592683
  lightness: 0.07930277846753597
  saturation: 0.01129442686215043
  rhythmicContrast: 0.6076483780052513
purpose: []
